services:
  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    # 🌟 비밀번호 자리를 mysql 서비스 바로 밑으로 칼각 맞춰 이동했습니다!
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "70:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge